//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabbit
    {
        public int RabbitID { get; set; }
        public int Owner { get; set; }
        public int Age { get; set; }
    
        public virtual Owner Owner1 { get; set; }
    }
}
